printing_site/config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('main_site.urls')),
]

printing_site/main_site/urls.py
from django.conf.urls import url
from .views import *

app_name = "main_site"
urlpatterns = [
    url(r'metal/', MetalTemplateView.as_view(), name="metal"),
    url(r'sintering/', SinteringTemplateView.as_view(), name="sintering"),
    url(r'farm/', FarmTemplateView.as_view(), name="farm"),
    url(r'contacts/', ContactsTemplateView.as_view(), name="contacts"),
    url(r'materials/', MaterialsTemplateView.as_view(), name="materials"),
    url(r'^$', MainTemplateView.as_view(), name="main"),
]

printing_site/main_site/models.py
from django.core.validators import RegexValidator
from django.db import models


class Contacts(models.Model):
    name = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?7?\d{9,13}$',
                                 message="Phone number must be entered in the format: '+79999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=13, blank=True)

    def __str__(self):
        return self.name

printing_site/main_site/forms.py
from django import forms
from .models import Contacts


class OrderForm(forms.ModelForm):
    # file = forms.FileField()
    # message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Contacts
        fields = ['name', 'email', 'phone_number']

printing_site/main_site/views.py
from django.views.generic import TemplateView, FormView


class MainTemplateView(TemplateView):
    template_name = "pages/main.html"
    title = 'Главная'

    menu = {'#technologies': 'Технологии', '#materials': 'Материалы', '#price': 'Цены',
            '#equlation': 'Расчет прочности', '#order': 'Заказ и доставка'}


class SinteringTemplateView(TemplateView):
    template_name = "pages/sintering.html"
    title = 'Спекание'

class MetalTemplateView(TemplateView):
    template_name = "pages/metal.html"
    title = 'Металл'


class PrintingTemplateView(TemplateView):
    template_name = "pages/metal.html"
    title = 'Печать'


class FarmTemplateView(TemplateView):
    template_name = "pages/farm.html"
    title = '3D Ферма'


class ContactsTemplateView(TemplateView):
    template_name = "pages/contacts.html"
    title = 'Контакты'


class MaterialsTemplateView(TemplateView):
    template_name = "pages/materials.html"
    title = 'Материалы'

printing_site/main_site/templates/components/slider.html
<!--{% load static %}-->

<!--<div class="slider">-->
<!--    <div class="slider_block">-->
<!--        <div class="slider__text">-->
<!--            <h1>3D ПЕЧАТЬ МЕТАЛЛОМ 316l</h1>-->
<!--            <p>Первая доступная печать металлом в России</p>-->
<!--        </div>-->
<!--        <input type="submit" value="Рассчитать стоимость">-->
<!--    </div>-->
<!--    <img src="{% static 'images/slider_gif(1).gif' %}" alt="slider gif"  width="500" height="380" />-->
<!--</div>-->

printing_site/main_site/templates/materials/fdm.html
{% load static %}

<div class="container flex-container align-center">
        <h2 class="section__title">FDM материалы</h2>
    </div>
    <div class="container flex-container align-center card-container">
        <div class="card material__card align-center">
          <img class="card-img-top" src="{% static 'images/materials/fdm_pc.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">PC (поликарбонат)</h5>
            <p class="card-text">Применяется в офтальмологии (для изготовления линз). Благодаря высокому коэффициенту светопропускания используется в качестве аналога стекла. Плавится при температуре 250-300⁰С, что нужно учитывать при выборе принтера. В среднем в три раза дороже ABS-пластика.</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_nylon.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">Нейлон</h5>
            <p class="card-text">Прочный, пластичный, химически устойчивый материал. Плавится при температуре около 250⁰С. При нагревании не выделяет токсичных паров, но сильно впитывает воду. Используется для создания прочных деталей и деталей с небольшим удельным весом.</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_pla.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">PLA (полилактид)</h5>
            <p class="card-text">Безусловный лидер рынка материалов для FDM печати – экологичный, биосовместимый, термопластичный состав. В основе его производства – кукуруза и сахарный тростник, благодаря чему изделия из этого типа пластика с успехом используются в быту. Его применяют для изготовления игрушек, посуды, сувенирной продукции, элементов корпусов для бытовой техники, дизайнерских моделей, упаковки для пищевых продуктов, лекарств, хирургической нити.</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_abs.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">ABS</h5>
            <p class="card-text"> самый популярный в области 3D прототипирования термостойкий пластик, который, тем не менее, не может считаться одним из наиболее востребованных. Преимущества – долговечность, механическая прочность, устойчивость к влаге, маслам, широкому спектру кислот и повышенным температурам.</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_formax.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">ForMax</h5>
            <p class="card-text">Инженерный пластик наполненный углеволокном. Материал зарекомендовал себя как обладатель низкой усадки, высокой прочности и жесткости напечатанных изделий,</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_hdpe.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">HDPE (полиэтилен высокой плотности)</h5>
            <p class="card-text">Это одна из наиболее востребованных во всем мире разновидностей пластика для 3D печати. Материал очень легко плавится и застывает в рекордно короткие сроки</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_pet.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">PET (полиэтилентерефталат)</h5>
            <p class="card-text">Пищевая и медицинская тара изготавливается в основном из этого материала с очень сложным названием. Главное его преимущество – высокая химическая стойкость, он неподвержен разрушительному воздействию широкого спектра кислот и щелочей, устойчив к износу и широкому диапазону температур</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_wood.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">Wood (Имитаторы древесины)</h5>
            <p class="card-text">Изделия визуально, и функционально ничем не уступают аналогам из натурального дерева – изделиям даже присущ характерный древесный аромат</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_laybrick.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">Laybrick (имитатор песчаника)</h5>
            <p class="card-text">Материал с высокими эстетическими и эксплуатационными характеристиками. Связующий материал, взятый за основу для создания этого типа материала, смешан с минеральным наполнителем – этим и объясняется оригинальная текстура получаемых изделий.</p>
          </div>
        </div>
        <div class="card material__card">
          <img class="card-img-top" src="{% static 'images/materials/fdm_bronzefill.jpg' %}" alt="Card image cap">
          <div class="card-body text-center">
            <h5 class="card-title">BronzeFill (имитатор металла)</h5>
            <p class="card-text">Это практически прозрачный пластик на основе PLA, в состав которого входит также бронзовый наполнитель. Готовые 3D объекты прекрасно реагируют на постобработку – шлифовку, полировку – и визуально выглядят, как цельнометаллические, однако забывать о том, что в основе – термопластик, все же не стоит.</p>
        </div>
    </div>
</div>

printing_site/main_site/templates/materials/metal.html
{% load static %}

<div class="container flex-container align-center">
    <h2 class="section__title">Печать металлом</h2>
</div>

<div class="container flex-container align-center">
    <div class="card direction-row metal__card">
      <img class="metal__card__img " src="{% static 'images/materials/metal.jpg' %}" alt="Card image cap">
      <div class="card-body text-center">
        <h3 class="card-title">Нержавеющая стать 316l</h3>
        <div class="metal__card-body">
            <p class="metal__card-text">Новый материал печати металлом на 90% состоит из порошка нержавеющей стали и 10% связующего.
                После удалаения связующего и обработки сыгрца в муфельной печи металлическое изделие готово.
                Мы предоставляем уникальный подход позволяющий снизить цену 5-10 раз по сравнению с технологиями лазерного спекания.
                <a href="{% url 'main_site:farm' %}" class="wow_offer">Нажми сюда, чтобы узнать больше про процесс печати металлом</a>
            </p>
            <ul class="metal__card-list">
                <li>Цена<span>от 100 до 150 руб./см3</span></li>
                <li>Предел прочности<span>561 MPa</span></li>
                <li>Предел текучести<span>251 MPa</span></li>
                <li>Относительное удлиннение<span>53%</span></li>
                <li>Твердость по Виккерсу<span>128HV10</span></li>
            </ul>
        </div>
      </div>
    </div>
</div>

printing_site/main_site/templates/materials/uv_lcd.html
{% load static %}

<div class="container flex-container align-center">
    <h2 class="section__title">Фотополимеры</h2>
</div>

<div class="container flex-container align-center card-container">
    <div class="card material__card align-center">
      <img class="card-img-top" src="{% static 'images/materials/lcd_castable.jpg' %}" alt="Card image cap">
      <div class="card-body text-center">
        <h5 class="card-title">Выжигаемый фотополимер Dental Castable</h5>
        <p class="card-text">Специально разработан для профессиональных задач стоматологов и ювелиров..</p>
      </div>
    </div>
    <div class="card material__card align-center">
      <img class="card-img-top" src="{% static 'images/materials/lcd_original.jpg' %}" alt="Card image cap">
      <div class="card-body text-center">
        <h5 class="card-title">Фотополимер Photon</h5>
        <p class="card-text">Базовый материал для качественной печати. 12 цветов.</p>
        <ul class="colors">
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
            <li class="color-white"></li>
        </ul>
      </div>
    </div>
    <div class="card material__card align-center">
      <img class="card-img-top" src="{% static 'images/materials/lcd_surgical.jpg' %}" alt="Card image cap">
      <div class="card-body text-center">
        <h5 class="card-title">Liquid Dental Surgical</h5>
        <p class="card-text">Применяется для изготовления хирургических шаблонов и моделей для планирования операций</p>
      </div>
    </div>
</div>

printing_site/main_site/templates/pages/base.html
<!doctype html>
<html lang="ru">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Dosis&family=Titillium+Web:ital,wght@1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Spectral+SC:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet">    {% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
    <header class="header">
        <a class="header__logo" href="{% url 'main_site:main' %}">
            <span class="logo-red">
                feed metal
            </span>
        </a>
        <ul class="navbar">
            <li><a class="bg-white" href="{% url 'main_site:metal' %}">ПЕЧАТЬ МЕТАЛЛОМ</a></li>
            <li><a class="bg-white" href="{% url 'main_site:materials' %}">МАТЕРИАЛЫ</a></li>
            <li><a class="bg-white" href="{% url 'main_site:farm' %}">3D ФЕРМА</a></li>
            <li><a class="bg-white" href="{% url 'main_site:sintering' %}">СПЕКАНИЕ</a></li>
            <li><a class="bg-white">УСЛУГИ</a></li>
            <li><a class="bg-white" href="{% url 'main_site:contacts' %}">КОНТАКТЫ</a></li>
        </ul>
    </header>
            {% block content %}
            {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<!--    <script src="{% static 'js/main.js'%}"></script>-->
</body>
</html>

printing_site/main_site/templates/pages/farm.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}Ателье 3D печать{% endblock %}

{% block content %}
<section>
        <div class="contact-info">
            <h3><big>Телефон/whatsup:</big>             +79043328940</h3>
            <h3><big>Telegram:</big>                    @Ruby_Roid</h3>
            <h3><big>Email:</big>                       rubymazeroid@gmail.com</h3>
            <h3><big>Офис:</big>                         Санкт-Петербург, ул. Шпалерная дом 51</h3>
        </div>
</section>
{% endblock %}

printing_site/main_site/templates/pages/main.html
{% extends 'pages/base.html' %}

{% load static %}

{% block title %}3D ФЕРМА{% endblock %}

{% block content %}
    <div class="first-screen">
        <div class="first-screen__left">
                <h2 class="first-screen__left__title">3D ферма</h2>
                <div class="send-file-block">
                    <h2 class="send-file__title">Загрузите файл в формате STL,SLDPT или архив для рассчета стоимости</h2>
                    <input type="file" value="выбрать файл">
                    <input type="text" onfocus="this.value=''" value="Введите телефон для обратной связи">
                    <input  class="send-file__comment" onfocus="this.value=''"  type="text" value="Оставьте дополнительную информацию если требуется">
                    <input type="submit" value="Отправить запрос">
                </div>
        </div>
        <div class="first-screen__right">
                <input id="calc-btn" type="button" value="Консультация инженера">
                <img src="{% static 'images/image_01.jpg' %}" alt="">
                <div class="first-screen__right__text-block">
                    <div class="first-screen__right__title">Самая доступная печать металлом в России</div>
                        <h2>Профессиональное оборудование</h2>
                        <h2>Печать металлом от 100 руб/см3</h2>
                        <h2>Материал: Нержавеющая сталь 316l</h2>
                        <h2>CAD моделирование 700 руб/час</h2>
                        <h2>График работы: Пн-Пт с 08.00 до 20.00</h2>
                        <h2>E-mail: feedmetal@gmail.com</h2>
                        <h2>Тел.: +7 904 332-89-40</h2>
                    </div>
            <input id="right_btn" type="submit" value="Консультация инженера">
        </div>
    </div>
    <div class="equipment">
        <div class="container flex-container align-center direction-column">
            <h2 class="section__title">ТЕХНОЛОГИИ И УСЛУГИ</h2>
            <p class="section__subtitle">Парк оборудования позволяет в кротчайшие сроки выпорлнять серийные заказы</p>
        </div>
        <div class="container flex-container align-center">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">технология</th>
                  <th scope="col">Зона печати</th>
                  <th scope="col">Точность</th>
                  <th scope="col">Цена</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">FDM</th>
                  <td>до 400х400х450 мм</td>
                  <td>0.4 мм</td>
                  <td>от 8 руб./см3</td>
                </tr>
                <tr>
                  <th scope="row">Фотополимерная печать</th>
                  <td>92х120х200 мм</td>
                  <td>0.043 мм</td>
                  <td>от 30 руб./см3</td>
                </tr>
                <tr>
                  <th scope="row">Печать металлом</th>
                  <td>270х210х200 мм</td>
                  <td>0.4 мм</td>
                  <td>от 100 руб./см3</td>
                </tr>
                <tr>
                  <th scope="row">CAD моделирование<th>
                  <th></th>
                  <td>700 руб./час</td>
                </tr>
                <tr>
                  <th scope="row">Поверхностное моделирование<th>
                  <th></th>
                  <td>1000 руб./час</td>
                </tr>
                <tr>
                  <th scope="row">3D сканирование<th>
                  <th></th>
                  <td>от 3000 руб.</td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
    <div class="materials">
        <div class="container">
            <div class="materials__block">
                <div>
                    <div class="materials__title">
                            <h1>Материалы</h1>
                    </div>
                    <div class="materials_text">
                            Металлонаполненный пластик - представляет
                            собой инновационную нить для
                            для производства деталей из стали марки 316L.
                    </div>
                </div>
                <img src="{% static 'images/filament.png' %}" alt="">
            </div>
            <div class="material-table">
                    <h1>Характеристики</h1>
                   <div class="divTable">
                        <div class="div-table-col">
                            <div class="divRow">
                                <div class="divCell">Предел прочности</div>
                                <div  class="divCell">Предел текучести</div>
                                <div  class="divCell">Относительное удлиннение</div>
                                <div  class="divCell">Твердость по Виккерсу</div>
                             </div>
                        </div>
                        <div class="div-table-col">
                            <div class="divRow">
                                  <div class="divCell">561 MPa</div>
                                <div class="divCell">251 MPa</div>
                                <div class="divCell">53%</div>
                                <div class="divCell">128HV10</div>
                            </div>
                        </div>
                  </div>
            </div>
        </div>
    </div>
    <div class="contacts">
        <h1>Контакты</h1>
        <img class="contacts-map" src="" alt="">
        <div class="contacts__body">
            <div class="divTable">
                <div class="div-table-col">
                    <div class="divRow">
                        <div class="divCell">Телефон:</div>
                        <div  class="divCell">Email:</div>
                        <div  class="divCell">Адресс</div>
                        <div  class="divCell">График работы:</div>
                     </div>
                </div>
                <div class="div-table-col">
                    <div class="divRow">
                          <div class="divCell">561 MPa</div>
                        <div class="divCell">251 MPa</div>
                        <div class="divCell">53%</div>
                        <div class="divCell">128HV10</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

printing_site/main_site/templates/pages/materials.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}Материалы{% endblock %}

{% block content %}
<section >
    <div class="container flex-container align-center">
        <div class="text-center materials-section__title">
            <h1 >Материалы</h1>
            <p>
                Напишите нам, чтобы узнать возможности и характеристики конкретного матриала.
                Если материал отсутствует среди перечисленных, мы закупим его под заказ.
            </p>
        </div>
    </div>
    {% include "materials/metal.html" %}
    {% include "materials/uv_lcd.html" %}
    {% include "materials/fdm.html" %}
</section>
{% endblock %}

printing_site/main_site/templates/pages/sintering.html
{% extends 'pages/base.html' %}
{% load static %}
{% block title %}
Ателье 3D печать
{% endblock %}

{% block content %}
<section>
        <div class="zaglushka-container">
        <h1>
            Страница в разработке.
        </h1>
    </div>
</section>
</div>


{% endblock %}

printing_site/main_site/templates/technologies/continuous_fiber.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

printing_site/main_site/templates/technologies/fdm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

printing_site/main_site/templates/technologies/large_fdm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

printing_site/main_site/templates/technologies/metal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

printing_site/main_site/templates/technologies/uv_lcd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

printing_site/main_site/templates/trash.html
<!--aside-->


<!--        <aside>-->
<!--        <nav>-->
<!--            <ul class="aside-menu">-->
<!--                <li class="active">{{view.title}}</li>-->
<!--                {% for key, values in view.menu.items %}-->
<!--                    <li><a href="{{key}}">{{ values }}</a></li>-->
<!--                {% endfor %}-->
<!--&lt;!&ndash;                    <li><a href="#technologies">Технологии</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                    <li><a href="#materials">Материалы</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                    <li><a href="#materials">Цены</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                    <li><a href="#equlation">Расчет прочности</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                    <li><a href="#order">Заказ и доставка</a></li>&ndash;&gt;-->
<!--            </ul>-->
<!--        </nav>-->
<!--        <h2>Адрес офиса</h2>-->
<!--        <p><img src="{% static 'images/map.png' %}" width="230" height="180" alt="Наш Офис"></p>-->
<!--    </aside>-->


        <ul class="navbar">
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%} bg-dark{%endif%}" href="{% url 'main_site:printing' %}">ПЕЧАТЬ    МЕТАЛЛОМ</a></li>
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%} bg-dark{%endif%}">МАТЕРИАЛЫ</a></li>
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%}bg-dark{%endif%}" href="{% url 'main_site:about' %}">3D ФЕРМА</a></li>
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%} bg-dark{%endif%}" href="{% url 'main_site:sintering' %}">СПЕКАНИЕ</a></li>
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%} bg-dark{%endif%}">УСЛУГИ</a></li>
            <li><a class="bg-white{% if 'Главная' in view.title %}bg-white{% elif 'О нас' in view.title %}bg-white{% else%} bg-dark{%endif%}" href="{% url 'main_site:contacts' %}">КОНТАКТЫ</a></li>
        </ul>